# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T19:17:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class NewsItem(BaseModel):
    created: Optional[str] = Field(None, title='News Published Time')
    ref: Optional[str] = Field(None, title='News Url')
    thumbnail: Optional[str] = Field(None, title='News Thumbnail')
    title: Optional[str] = Field(None, title='News Title')


class Mobile(Enum):
    integer_1 = 1


class Funcs(Enum):
    getLatestNewsForChatGPT = 'getLatestNewsForChatGPT'


class ApiResponse(BaseModel):
    getLatestNewsForChatGPT: List[NewsItem] = Field(
        ..., description='The list of latest news.', title='Result of Latest News'
    )
